version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=example
    ports:
      - '27017-27019:27017-27019'
    volumes:
      - ../data/mongodb_data:/data/db

volumes:
  mongodb_data_container:
    driver: local
