name: Github Pages Publish

on:
  push:
    branches:
      - disable

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: jinjat-data/gh-pages-deploy-action@v1.0
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          source-directory: backend/public
